process.roles=broker,controller
node.id=1
controller.quorum.voters=1@kafka-1:29093,2@kafka-2:29093,3@kafka-3:29093

listeners=PLAINTEXT://:29092,CONTROLLER://:29093,EXTERNAL://0.0.0.0:9092
advertised.listeners=PLAINTEXT://kafka-1:29092,EXTERNAL://localhost:${KAFKA_1_EXTERNAL_PORT}
listener.security.protocol.map=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
controller.listener.names=CONTROLLER
inter.broker.listener.name=PLAINTEXT

default.replication.factor=3
min.insync.replicas=2
offsets.topic.replication.factor=3
transaction.state.log.replication.factor=3
transaction.state.log.min.isr=2

log.dirs=/var/lib/kafka/data
log.retention.hours=72
log.segment.bytes=1073741824

num.network.threads=3
num.io.threads=8
num.partitions=6

socket.send.buffer.bytes=102400
socket.receive.buffer.bytes=102400
socket.request.max.bytes=104857600
